name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME:  datagpt

jobs:
  build-and-push:
    name: Build and Push to ACR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$IMAGE_NAME:${{ github.sha }} .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$IMAGE_NAME:${{ github.sha }}

    - name: Tag image as "latest"
      run: |
        docker tag ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$IMAGE_NAME:${{ github.sha }} ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$IMAGE_NAME:latest
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$IMAGE_NAME:latest
